interface CountryData {
  code: string; // The country code (e.g. "US", "IN")
  dialCode: string; // The dialing code (e.g. "+1", "+91")
  flag: string; // The flag code (e.g. "US", "IN")
  name: string;
  flagSvg: string;
}

const countryCodesData: CountryData[] = [
  {
    code: "AF",
    dialCode: "+93",
    flag: "AF",
    name: "Afghanistan",
    flagSvg: "https://flagcdn.com/32x24/af.webp",
  },
  {
    code: "AL",
    dialCode: "+355",
    flag: "AL",
    name: "Albania",
    flagSvg: "https://flagcdn.com/32x24/al.webp",
  },
  {
    code: "DZ",
    dialCode: "+213",
    flag: "DZ",
    name: "Algeria",
    flagSvg: "https://flagcdn.com/32x24/dz.webp",
  },
  {
    code: "AS",
    dialCode: "+1684",
    flag: "AS",
    name: "American Samoa",
    flagSvg: "https://flagcdn.com/32x24/as.webp",
  },
  {
    code: "AD",
    dialCode: "+376",
    flag: "AD",
    name: "Andorra",
    flagSvg: "https://flagcdn.com/32x24/ad.webp",
  },
  {
    code: "AO",
    dialCode: "+244",
    flag: "AO",
    name: "Angola",
    flagSvg: "https://flagcdn.com/32x24/ao.webp",
  },
  {
    code: "AI",
    dialCode: "+1264",
    flag: "AI",
    name: "Anguilla",
    flagSvg: "https://flagcdn.com/32x24/ai.webp",
  },
  {
    code: "AR",
    dialCode: "+54",
    flag: "AR",
    name: "Argentina",
    flagSvg: "https://flagcdn.com/32x24/ar.webp",
  },
  {
    code: "AM",
    dialCode: "+374",
    flag: "AM",
    name: "Armenia",
    flagSvg: "https://flagcdn.com/32x24/am.webp",
  },
  {
    code: "AU",
    dialCode: "+61",
    flag: "AU",
    name: "Australia",
    flagSvg: "https://flagcdn.com/32x24/au.webp",
  },
  {
    code: "AT",
    dialCode: "+43",
    flag: "AT",
    name: "Austria",
    flagSvg: "https://flagcdn.com/32x24/at.webp",
  },
  {
    code: "AZ",
    dialCode: "+994",
    flag: "AZ",
    name: "Azerbaijan",
    flagSvg: "https://flagcdn.com/32x24/az.webp",
  },
  {
    code: "BS",
    dialCode: "+1242",
    flag: "BS",
    name: "Bahamas",
    flagSvg: "https://flagcdn.com/32x24/bs.webp",
  },
  {
    code: "BH",
    dialCode: "+973",
    flag: "BH",
    name: "Bahrain",
    flagSvg: "https://flagcdn.com/32x24/bh.webp",
  },
  {
    code: "BD",
    dialCode: "+880",
    flag: "BD",
    name: "Bangladesh",
    flagSvg: "https://flagcdn.com/32x24/bd.webp",
  },
  {
    code: "BB",
    dialCode: "+1246",
    flag: "BB",
    name: "Barbados",
    flagSvg: "https://flagcdn.com/32x24/bb.webp",
  },
  {
    code: "BY",
    dialCode: "+375",
    flag: "BY",
    name: "Belarus",
    flagSvg: "https://flagcdn.com/32x24/by.webp",
  },
  {
    code: "BE",
    dialCode: "+32",
    flag: "BE",
    name: "Belgium",
    flagSvg: "https://flagcdn.com/32x24/be.webp",
  },
  {
    code: "BZ",
    dialCode: "+501",
    flag: "BZ",
    name: "Belize",
    flagSvg: "https://flagcdn.com/32x24/bz.webp",
  },
  {
    code: "BJ",
    dialCode: "+229",
    flag: "BJ",
    name: "Benin",
    flagSvg: "https://flagcdn.com/32x24/bj.webp",
  },
  {
    code: "BT",
    dialCode: "+975",
    flag: "BT",
    name: "Bhutan",
    flagSvg: "https://flagcdn.com/32x24/bt.webp",
  },
  {
    code: "BO",
    dialCode: "+591",
    flag: "BO",
    name: "Bolivia",
    flagSvg: "https://flagcdn.com/32x24/bo.webp",
  },
  {
    code: "BA",
    dialCode: "+387",
    flag: "BA",
    name: "Bosnia and Herzegovina",
    flagSvg: "https://flagcdn.com/32x24/ba.webp",
  },
  {
    code: "BW",
    dialCode: "+267",
    flag: "BW",
    name: "Botswana",
    flagSvg: "https://flagcdn.com/32x24/bw.webp",
  },
  {
    code: "BR",
    dialCode: "+55",
    flag: "BR",
    name: "Brazil",
    flagSvg: "https://flagcdn.com/32x24/br.webp",
  },
  {
    code: "BN",
    dialCode: "+673",
    flag: "BN",
    name: "Brunei",
    flagSvg: "https://flagcdn.com/32x24/bn.webp",
  },
  {
    code: "BG",
    dialCode: "+359",
    flag: "BG",
    name: "Bulgaria",
    flagSvg: "https://flagcdn.com/32x24/bg.webp",
  },
  {
    code: "BF",
    dialCode: "+226",
    flag: "BF",
    name: "Burkina Faso",
    flagSvg: "https://flagcdn.com/32x24/bf.webp",
  },
  {
    code: "BI",
    dialCode: "+257",
    flag: "BI",
    name: "Burundi",
    flagSvg: "https://flagcdn.com/32x24/bi.webp",
  },
  {
    code: "KH",
    dialCode: "+855",
    flag: "KH",
    name: "Cambodia",
    flagSvg: "https://flagcdn.com/32x24/kh.webp",
  },
  {
    code: "CM",
    dialCode: "+237",
    flag: "CM",
    name: "Cameroon",
    flagSvg: "https://flagcdn.com/32x24/cm.webp",
  },
  {
    code: "CA",
    dialCode: "+1",
    flag: "CA",
    name: "Canada",
    flagSvg: "https://flagcdn.com/32x24/ca.webp",
  },
  {
    code: "CV",
    dialCode: "+238",
    flag: "CV",
    name: "Cape Verde",
    flagSvg: "https://flagcdn.com/32x24/cv.webp",
  },
  {
    code: "KY",
    dialCode: "+1345",
    flag: "KY",
    name: "Cayman Islands",
    flagSvg: "https://flagcdn.com/32x24/ky.webp",
  },
  {
    code: "CF",
    dialCode: "+236",
    flag: "CF",
    name: "Central African Republic",
    flagSvg: "https://flagcdn.com/32x24/cf.webp",
  },
  {
    code: "TD",
    dialCode: "+235",
    flag: "TD",
    name: "Chad",
    flagSvg: "https://flagcdn.com/32x24/td.webp",
  },
  {
    code: "CL",
    dialCode: "+56",
    flag: "CL",
    name: "Chile",
    flagSvg: "https://flagcdn.com/32x24/cl.webp",
  },
  {
    code: "CN",
    dialCode: "+86",
    flag: "CN",
    name: "China",
    flagSvg: "https://flagcdn.com/32x24/cn.webp",
  },
  {
    code: "CO",
    dialCode: "+57",
    flag: "CO",
    name: "Colombia",
    flagSvg: "https://flagcdn.com/32x24/co.webp",
  },
  {
    code: "CR",
    dialCode: "+506",
    flag: "CR",
    name: "Costa Rica",
    flagSvg: "https://flagcdn.com/32x24/cr.webp",
  },
  {
    code: "HR",
    dialCode: "+385",
    flag: "HR",
    name: "Croatia",
    flagSvg: "https://flagcdn.com/32x24/hr.webp",
  },
  {
    code: "CU",
    dialCode: "+53",
    flag: "CU",
    name: "Cuba",
    flagSvg: "https://flagcdn.com/32x24/cu.webp",
  },
  {
    code: "CY",
    dialCode: "+357",
    flag: "CY",
    name: "Cyprus",
    flagSvg: "https://flagcdn.com/32x24/cy.webp",
  },
  {
    code: "CZ",
    dialCode: "+420",
    flag: "CZ",
    name: "Czech Republic",
    flagSvg: "https://flagcdn.com/32x24/cz.webp",
  },
  {
    code: "DR",
    dialCode: "+1-809",
    flag: "DO",
    name: "Dominican Republic",
    flagSvg: "https://flagcdn.com/32x24/do.webp",
  },
  {
    code: "DK",
    dialCode: "+45",
    flag: "DK",
    name: "Denmark",
    flagSvg: "https://flagcdn.com/32x24/dk.webp",
  },
  {
    code: "DJ",
    dialCode: "+253",
    flag: "DJ",
    name: "Djibouti",
    flagSvg: "https://flagcdn.com/32x24/dj.webp",
  },
  {
    code: "DM",
    dialCode: "+1767",
    flag: "DM",
    name: "Dominica",
    flagSvg: "https://flagcdn.com/32x24/dm.webp",
  },
  {
    code: "EC",
    dialCode: "+593",
    flag: "EC",
    name: "Ecuador",
    flagSvg: "https://flagcdn.com/32x24/ec.webp",
  },
  {
    code: "EG",
    dialCode: "+20",
    flag: "EG",
    name: "Egypt",
    flagSvg: "https://flagcdn.com/32x24/eg.webp",
  },
  {
    code: "SV",
    dialCode: "+503",
    flag: "SV",
    name: "El Salvador",
    flagSvg: "https://flagcdn.com/32x24/sv.webp",
  },
  {
    code: "GQ",
    dialCode: "+240",
    flag: "GQ",
    name: "Equatorial Guinea",
    flagSvg: "https://flagcdn.com/32x24/gq.webp",
  },
  {
    code: "ER",
    dialCode: "+291",
    flag: "ER",
    name: "Eritrea",
    flagSvg: "https://flagcdn.com/32x24/er.webp",
  },
  {
    code: "EE",
    dialCode: "+372",
    flag: "EE",
    name: "Estonia",
    flagSvg: "https://flagcdn.com/32x24/ee.webp",
  },
  {
    code: "ET",
    dialCode: "+251",
    flag: "ET",
    name: "Ethiopia",
    flagSvg: "https://flagcdn.com/32x24/et.webp",
  },
  {
    code: "FK",
    dialCode: "+500",
    flag: "FK",
    name: "Falkland Islands",
    flagSvg: "https://flagcdn.com/32x24/fk.webp",
  },
  {
    code: "FO",
    dialCode: "+298",
    flag: "FO",
    name: "Faroe Islands",
    flagSvg: "https://flagcdn.com/32x24/fo.webp",
  },
  {
    code: "FJ",
    dialCode: "+679",
    flag: "FJ",
    name: "Fiji",
    flagSvg: "https://flagcdn.com/32x24/fj.webp",
  },
  {
    code: "FI",
    dialCode: "+358",
    flag: "FI",
    name: "Finland",
    flagSvg: "https://flagcdn.com/32x24/fi.webp",
  },
  {
    code: "FR",
    dialCode: "+33",
    flag: "FR",
    name: "France",
    flagSvg: "https://flagcdn.com/32x24/fr.webp",
  },
  {
    code: "GA",
    dialCode: "+241",
    flag: "GA",
    name: "Gabon",
    flagSvg: "https://flagcdn.com/32x24/ga.webp",
  },
  {
    code: "GM",
    dialCode: "+220",
    flag: "GM",
    name: "Gambia",
    flagSvg: "https://flagcdn.com/32x24/gm.webp",
  },
  {
    code: "GE",
    dialCode: "+995",
    flag: "GE",
    name: "Georgia",
    flagSvg: "https://flagcdn.com/32x24/ge.webp",
  },
  {
    code: "DE",
    dialCode: "+49",
    flag: "DE",
    name: "Germany",
    flagSvg: "https://flagcdn.com/32x24/de.webp",
  },
  {
    code: "GH",
    dialCode: "+233",
    flag: "GH",
    name: "Ghana",
    flagSvg: "https://flagcdn.com/32x24/gh.webp",
  },
  {
    code: "GI",
    dialCode: "+350",
    flag: "GI",
    name: "Gibraltar",
    flagSvg: "https://flagcdn.com/32x24/gi.webp",
  },
  {
    code: "GR",
    dialCode: "+30",
    flag: "GR",
    name: "Greece",
    flagSvg: "https://flagcdn.com/32x24/gr.webp",
  },
  {
    code: "GL",
    dialCode: "+299",
    flag: "GL",
    name: "Greenland",
    flagSvg: "https://flagcdn.com/32x24/gl.webp",
  },
  {
    code: "GD",
    dialCode: "+1473",
    flag: "GD",
    name: "Grenada",
    flagSvg: "https://flagcdn.com/32x24/gd.webp",
  },
  {
    code: "GU",
    dialCode: "+1671",
    flag: "GU",
    name: "Guam",
    flagSvg: "https://flagcdn.com/32x24/gu.webp",
  },
  {
    code: "GT",
    dialCode: "+502",
    flag: "GT",
    name: "Guatemala",
    flagSvg: "https://flagcdn.com/32x24/gt.webp",
  },
  {
    code: "GN",
    dialCode: "+224",
    flag: "GN",
    name: "Guinea",
    flagSvg: "https://flagcdn.com/32x24/gn.webp",
  },
  {
    code: "GW",
    dialCode: "+245",
    flag: "GW",
    name: "Guinea-Bissau",
    flagSvg: "https://flagcdn.com/32x24/gw.webp",
  },
  {
    code: "GY",
    dialCode: "+592",
    flag: "GY",
    name: "Guyana",
    flagSvg: "https://flagcdn.com/32x24/gy.webp",
  },
  {
    code: "HT",
    dialCode: "+509",
    flag: "HT",
    name: "Haiti",
    flagSvg: "https://flagcdn.com/32x24/ht.webp",
  },
  {
    code: "HN",
    dialCode: "+504",
    flag: "HN",
    name: "Honduras",
    flagSvg: "https://flagcdn.com/32x24/hn.webp",
  },
  {
    code: "HK",
    dialCode: "+852",
    flag: "HK",
    name: "Hong Kong",
    flagSvg: "https://flagcdn.com/32x24/hk.webp",
  },
  {
    code: "HU",
    dialCode: "+36",
    flag: "HU",
    name: "Hungary",
    flagSvg: "https://flagcdn.com/32x24/hu.webp",
  },
  {
    code: "IS",
    dialCode: "+354",
    flag: "IS",
    name: "Iceland",
    flagSvg: "https://flagcdn.com/32x24/is.webp",
  },
  {
    code: "IN",
    dialCode: "+91",
    flag: "IN",
    name: "India",
    flagSvg: "https://flagcdn.com/32x24/in.webp",
  },
  {
    code: "ID",
    dialCode: "+62",
    flag: "ID",
    name: "Indonesia",
    flagSvg: "https://flagcdn.com/32x24/id.webp",
  },
  {
    code: "IR",
    dialCode: "+98",
    flag: "IR",
    name: "Iran",
    flagSvg: "https://flagcdn.com/32x24/ir.webp",
  },
  {
    code: "IQ",
    dialCode: "+964",
    flag: "IQ",
    name: "Iraq",
    flagSvg: "https://flagcdn.com/32x24/iq.webp",
  },
  {
    code: "IE",
    dialCode: "+353",
    flag: "IE",
    name: "Ireland",
    flagSvg: "https://flagcdn.com/32x24/ie.webp",
  },
  {
    code: "IL",
    dialCode: "+972",
    flag: "IL",
    name: "Israel",
    flagSvg: "https://flagcdn.com/32x24/il.webp",
  },
  {
    code: "IT",
    dialCode: "+39",
    flag: "IT",
    name: "Italy",
    flagSvg: "https://flagcdn.com/32x24/it.webp",
  },
  {
    code: "JM",
    dialCode: "+1876",
    flag: "JM",
    name: "Jamaica",
    flagSvg: "https://flagcdn.com/32x24/jm.webp",
  },
  {
    code: "JP",
    dialCode: "+81",
    flag: "JP",
    name: "Japan",
    flagSvg: "https://flagcdn.com/32x24/jp.webp",
  },
  {
    code: "JO",
    dialCode: "+962",
    flag: "JO",
    name: "Jordan",
    flagSvg: "https://flagcdn.com/32x24/jo.webp",
  },
  {
    code: "KZ",
    dialCode: "+7",
    flag: "KZ",
    name: "Kazakhstan",
    flagSvg: "https://flagcdn.com/32x24/kz.webp",
  },
  {
    code: "KE",
    dialCode: "+254",
    flag: "KE",
    name: "Kenya",
    flagSvg: "https://flagcdn.com/32x24/ke.webp",
  },
  {
    code: "KI",
    dialCode: "+686",
    flag: "KI",
    name: "Kiribati",
    flagSvg: "https://flagcdn.com/32x24/ki.webp",
  },
  {
    code: "KW",
    dialCode: "+965",
    flag: "KW",
    name: "Kuwait",
    flagSvg: "https://flagcdn.com/32x24/kw.webp",
  },
  {
    code: "KG",
    dialCode: "+996",
    flag: "KG",
    name: "Kyrgyzstan",
    flagSvg: "https://flagcdn.com/32x24/kg.webp",
  },
  {
    code: "LA",
    dialCode: "+856",
    flag: "LA",
    name: "Laos",
    flagSvg: "https://flagcdn.com/32x24/la.webp",
  },
  {
    code: "LV",
    dialCode: "+371",
    flag: "LV",
    name: "Latvia",
    flagSvg: "https://flagcdn.com/32x24/lv.webp",
  },
  {
    code: "LB",
    dialCode: "+961",
    flag: "LB",
    name: "Lebanon",
    flagSvg: "https://flagcdn.com/32x24/lb.webp",
  },
  {
    code: "LS",
    dialCode: "+266",
    flag: "LS",
    name: "Lesotho",
    flagSvg: "https://flagcdn.com/32x24/ls.webp",
  },
  {
    code: "LR",
    dialCode: "+231",
    flag: "LR",
    name: "Liberia",
    flagSvg: "https://flagcdn.com/32x24/lr.webp",
  },
  {
    code: "LY",
    dialCode: "+218",
    flag: "LY",
    name: "Libya",
    flagSvg: "https://flagcdn.com/32x24/ly.webp",
  },
  {
    code: "LI",
    dialCode: "+423",
    flag: "LI",
    name: "Liechtenstein",
    flagSvg: "https://flagcdn.com/32x24/li.webp",
  },
  {
    code: "LT",
    dialCode: "+370",
    flag: "LT",
    name: "Lithuania",
    flagSvg: "https://flagcdn.com/32x24/lt.webp",
  },
  {
    code: "LU",
    dialCode: "+352",
    flag: "LU",
    name: "Luxembourg",
    flagSvg: "https://flagcdn.com/32x24/lu.webp",
  },
  {
    code: "MO",
    dialCode: "+853",
    flag: "MO",
    name: "Macao",
    flagSvg: "https://flagcdn.com/32x24/mo.webp",
  },
  {
    code: "MK",
    dialCode: "+389",
    flag: "MK",
    name: "North Macedonia",
    flagSvg: "https://flagcdn.com/32x24/mk.webp",
  },
  {
    code: "MG",
    dialCode: "+261",
    flag: "MG",
    name: "Madagascar",
    flagSvg: "https://flagcdn.com/32x24/mg.webp",
  },
  {
    code: "MW",
    dialCode: "+265",
    flag: "MW",
    name: "Malawi",
    flagSvg: "https://flagcdn.com/32x24/mw.webp",
  },
  {
    code: "MY",
    dialCode: "+60",
    flag: "MY",
    name: "Malaysia",
    flagSvg: "https://flagcdn.com/32x24/my.webp",
  },
  {
    code: "MV",
    dialCode: "+960",
    flag: "MV",
    name: "Maldives",
    flagSvg: "https://flagcdn.com/32x24/mv.webp",
  },
  {
    code: "ML",
    dialCode: "+223",
    flag: "ML",
    name: "Mali",
    flagSvg: "https://flagcdn.com/32x24/ml.webp",
  },
  {
    code: "MT",
    dialCode: "+356",
    flag: "MT",
    name: "Malta",
    flagSvg: "https://flagcdn.com/32x24/mt.webp",
  },
  {
    code: "MH",
    dialCode: "+692",
    flag: "MH",
    name: "Marshall Islands",
    flagSvg: "https://flagcdn.com/32x24/mh.webp",
  },
  {
    code: "MQ",
    dialCode: "+596",
    flag: "MQ",
    name: "Martinique",
    flagSvg: "https://flagcdn.com/32x24/mq.webp",
  },
  {
    code: "MR",
    dialCode: "+222",
    flag: "MR",
    name: "Mauritania",
    flagSvg: "https://flagcdn.com/32x24/mr.webp",
  },
  {
    code: "MU",
    dialCode: "+230",
    flag: "MU",
    name: "Mauritius",
    flagSvg: "https://flagcdn.com/32x24/mu.webp",
  },
  {
    code: "YT",
    dialCode: "+262",
    flag: "YT",
    name: "Mayotte",
    flagSvg: "https://flagcdn.com/32x24/yt.webp",
  },
  {
    code: "MX",
    dialCode: "+52",
    flag: "MX",
    name: "Mexico",
    flagSvg: "https://flagcdn.com/32x24/mx.webp",
  },
  {
    code: "FM",
    dialCode: "+691",
    flag: "FM",
    name: "Micronesia",
    flagSvg: "https://flagcdn.com/32x24/fm.webp",
  },
  {
    code: "MD",
    dialCode: "+373",
    flag: "MD",
    name: "Moldova",
    flagSvg: "https://flagcdn.com/32x24/md.webp",
  },
  {
    code: "MC",
    dialCode: "+377",
    flag: "MC",
    name: "Monaco",
    flagSvg: "https://flagcdn.com/32x24/mc.webp",
  },
  {
    code: "MN",
    dialCode: "+976",
    flag: "MN",
    name: "Mongolia",
    flagSvg: "https://flagcdn.com/32x24/mn.webp",
  },
  {
    code: "ME",
    dialCode: "+382",
    flag: "ME",
    name: "Montenegro",
    flagSvg: "https://flagcdn.com/32x24/me.webp",
  },
  {
    code: "MS",
    dialCode: "+1664",
    flag: "MS",
    name: "Montserrat",
    flagSvg: "https://flagcdn.com/32x24/ms.webp",
  },
  {
    code: "MA",
    dialCode: "+212",
    flag: "MA",
    name: "Morocco",
    flagSvg: "https://flagcdn.com/32x24/ma.webp",
  },
  {
    code: "MZ",
    dialCode: "+258",
    flag: "MZ",
    name: "Mozambique",
    flagSvg: "https://flagcdn.com/32x24/mz.webp",
  },
  {
    code: "MM",
    dialCode: "+95",
    flag: "MM",
    name: "Myanmar",
    flagSvg: "https://flagcdn.com/32x24/mm.webp",
  },
  {
    code: "NA",
    dialCode: "+264",
    flag: "NA",
    name: "Namibia",
    flagSvg: "https://flagcdn.com/32x24/na.webp",
  },
  {
    code: "NR",
    dialCode: "+674",
    flag: "NR",
    name: "Nauru",
    flagSvg: "https://flagcdn.com/32x24/nr.webp",
  },
  {
    code: "NP",
    dialCode: "+977",
    flag: "NP",
    name: "Nepal",
    flagSvg: "https://flagcdn.com/32x24/np.webp",
  },
  {
    code: "NL",
    dialCode: "+31",
    flag: "NL",
    name: "Netherlands",
    flagSvg: "https://flagcdn.com/32x24/nl.webp",
  },
  {
    code: "NC",
    dialCode: "+687",
    flag: "NC",
    name: "New Caledonia",
    flagSvg: "https://flagcdn.com/32x24/nc.webp",
  },
  {
    code: "NZ",
    dialCode: "+64",
    flag: "NZ",
    name: "New Zealand",
    flagSvg: "https://flagcdn.com/32x24/nz.webp",
  },
  {
    code: "NI",
    dialCode: "+505",
    flag: "NI",
    name: "Nicaragua",
    flagSvg: "https://flagcdn.com/32x24/ni.webp",
  },
  {
    code: "NE",
    dialCode: "+227",
    flag: "NE",
    name: "Niger",
    flagSvg: "https://flagcdn.com/32x24/ne.webp",
  },
  {
    code: "NG",
    dialCode: "+234",
    flag: "NG",
    name: "Nigeria",
    flagSvg: "https://flagcdn.com/32x24/ng.webp",
  },
  {
    code: "NU",
    dialCode: "+683",
    flag: "NU",
    name: "Niue",
    flagSvg: "https://flagcdn.com/32x24/nu.webp",
  },
  {
    code: "NF",
    dialCode: "+672",
    flag: "NF",
    name: "Norfolk Island",
    flagSvg: "https://flagcdn.com/32x24/nf.webp",
  },
  {
    code: "MP",
    dialCode: "+1670",
    flag: "MP",
    name: "Northern Mariana Islands",
    flagSvg: "https://flagcdn.com/32x24/mp.webp",
  },
  {
    code: "NO",
    dialCode: "+47",
    flag: "NO",
    name: "Norway",
    flagSvg: "https://flagcdn.com/32x24/no.webp",
  },
  {
    code: "OM",
    dialCode: "+968",
    flag: "OM",
    name: "Oman",
    flagSvg: "https://flagcdn.com/32x24/om.webp",
  },
  {
    code: "PK",
    dialCode: "+92",
    flag: "PK",
    name: "Pakistan",
    flagSvg: "https://flagcdn.com/32x24/pk.webp",
  },
  {
    code: "PW",
    dialCode: "+680",
    flag: "PW",
    name: "Palau",
    flagSvg: "https://flagcdn.com/32x24/pw.webp",
  },
  {
    code: "PA",
    dialCode: "+507",
    flag: "PA",
    name: "Panama",
    flagSvg: "https://flagcdn.com/32x24/pa.webp",
  },
  {
    code: "PG",
    dialCode: "+675",
    flag: "PG",
    name: "Papua New Guinea",
    flagSvg: "https://flagcdn.com/32x24/pg.webp",
  },
  {
    code: "PY",
    dialCode: "+595",
    flag: "PY",
    name: "Paraguay",
    flagSvg: "https://flagcdn.com/32x24/py.webp",
  },
  {
    code: "PE",
    dialCode: "+51",
    flag: "PE",
    name: "Peru",
    flagSvg: "https://flagcdn.com/32x24/pe.webp",
  },
  {
    code: "PH",
    dialCode: "+63",
    flag: "PH",
    name: "Philippines",
    flagSvg: "https://flagcdn.com/32x24/ph.webp",
  },
  {
    code: "PL",
    dialCode: "+48",
    flag: "PL",
    name: "Poland",
    flagSvg: "https://flagcdn.com/32x24/pl.webp",
  },
  {
    code: "PT",
    dialCode: "+351",
    flag: "PT",
    name: "Portugal",
    flagSvg: "https://flagcdn.com/32x24/pt.webp",
  },
  {
    code: "PR",
    dialCode: "+1787",
    flag: "PR",
    name: "Puerto Rico",
    flagSvg: "https://flagcdn.com/32x24/pr.webp",
  },
  {
    code: "QA",
    dialCode: "+974",
    flag: "QA",
    name: "Qatar",
    flagSvg: "https://flagcdn.com/32x24/qa.webp",
  },
  {
    code: "RO",
    dialCode: "+40",
    flag: "RO",
    name: "Romania",
    flagSvg: "https://flagcdn.com/32x24/ro.webp",
  },
  {
    code: "RU",
    dialCode: "+7",
    flag: "RU",
    name: "Russia",
    flagSvg: "https://flagcdn.com/32x24/ru.webp",
  },
  {
    code: "RW",
    dialCode: "+250",
    flag: "RW",
    name: "Rwanda",
    flagSvg: "https://flagcdn.com/32x24/rw.webp",
  },
  {
    code: "RE",
    dialCode: "+262",
    flag: "RE",
    name: "Réunion",
    flagSvg: "https://flagcdn.com/32x24/re.webp",
  },
  {
    code: "BL",
    dialCode: "+590",
    flag: "BL",
    name: "Saint Barthélemy",
    flagSvg: "https://flagcdn.com/32x24/bl.webp",
  },
  {
    code: "SH",
    dialCode: "+290",
    flag: "SH",
    name: "Saint Helena",
    flagSvg: "https://flagcdn.com/32x24/sh.webp",
  },
  {
    code: "KN",
    dialCode: "+1869",
    flag: "KN",
    name: "Saint Kitts and Nevis",
    flagSvg: "https://flagcdn.com/32x24/kn.webp",
  },
  {
    code: "LC",
    dialCode: "+1758",
    flag: "LC",
    name: "Saint Lucia",
    flagSvg: "https://flagcdn.com/32x24/lc.webp",
  },
  {
    code: "MF",
    dialCode: "+590",
    flag: "MF",
    name: "Saint Martin",
    flagSvg: "https://flagcdn.com/32x24/mf.webp",
  },
  {
    code: "PM",
    dialCode: "+508",
    flag: "PM",
    name: "Saint Pierre and Miquelon",
    flagSvg: "https://flagcdn.com/32x24/pm.webp",
  },
  {
    code: "VC",
    dialCode: "+1784",
    flag: "VC",
    name: "Saint Vincent and the Grenadines",
    flagSvg: "https://flagcdn.com/32x24/vc.webp",
  },
  {
    code: "WS",
    dialCode: "+685",
    flag: "WS",
    name: "Samoa",
    flagSvg: "https://flagcdn.com/32x24/ws.webp",
  },
  {
    code: "SM",
    dialCode: "+378",
    flag: "SM",
    name: "San Marino",
    flagSvg: "https://flagcdn.com/32x24/sm.webp",
  },
  {
    code: "ST",
    dialCode: "+239",
    flag: "ST",
    name: "São Tomé and Príncipe",
    flagSvg: "https://flagcdn.com/32x24/st.webp",
  },
  {
    code: "SA",
    dialCode: "+966",
    flag: "SA",
    name: "Saudi Arabia",
    flagSvg: "https://flagcdn.com/32x24/sa.webp",
  },
  {
    code: "SN",
    dialCode: "+221",
    flag: "SN",
    name: "Senegal",
    flagSvg: "https://flagcdn.com/32x24/sn.webp",
  },
  {
    code: "RS",
    dialCode: "+381",
    flag: "RS",
    name: "Serbia",
    flagSvg: "https://flagcdn.com/32x24/rs.webp",
  },
  {
    code: "SC",
    dialCode: "+248",
    flag: "SC",
    name: "Seychelles",
    flagSvg: "https://flagcdn.com/32x24/sc.webp",
  },
  {
    code: "SL",
    dialCode: "+232",
    flag: "SL",
    name: "Sierra Leone",
    flagSvg: "https://flagcdn.com/32x24/sl.webp",
  },
  {
    code: "SG",
    dialCode: "+65",
    flag: "SG",
    name: "Singapore",
    flagSvg: "https://flagcdn.com/32x24/sg.webp",
  },
  {
    code: "SX",
    dialCode: "+1721",
    flag: "SX",
    name: "Sint Maarten",
    flagSvg: "https://flagcdn.com/32x24/sx.webp",
  },
  {
    code: "SK",
    dialCode: "+421",
    flag: "SK",
    name: "Slovakia",
    flagSvg: "https://flagcdn.com/32x24/sk.webp",
  },
  {
    code: "SI",
    dialCode: "+386",
    flag: "SI",
    name: "Slovenia",
    flagSvg: "https://flagcdn.com/32x24/si.webp",
  },
  {
    code: "SB",
    dialCode: "+677",
    flag: "SB",
    name: "Solomon Islands",
    flagSvg: "https://flagcdn.com/32x24/sb.webp",
  },
  {
    code: "SO",
    dialCode: "+252",
    flag: "SO",
    name: "Somalia",
    flagSvg: "https://flagcdn.com/32x24/so.webp",
  },
  {
    code: "ZA",
    dialCode: "+27",
    flag: "ZA",
    name: "South Africa",
    flagSvg: "https://flagcdn.com/32x24/za.webp",
  },
  {
    code: "GS",
    dialCode: "+500",
    flag: "GS",
    name: "South Georgia and the South Sandwich Islands",
    flagSvg: "https://flagcdn.com/32x24/gs.webp",
  },
  {
    code: "KR",
    dialCode: "+82",
    flag: "KR",
    name: "South Korea",
    flagSvg: "https://flagcdn.com/32x24/kr.webp",
  },
  {
    code: "SS",
    dialCode: "+211",
    flag: "SS",
    name: "South Sudan",
    flagSvg: "https://flagcdn.com/32x24/ss.webp",
  },
  {
    code: "ES",
    dialCode: "+34",
    flag: "ES",
    name: "Spain",
    flagSvg: "https://flagcdn.com/32x24/es.webp",
  },
  {
    code: "LK",
    dialCode: "+94",
    flag: "LK",
    name: "Sri Lanka",
    flagSvg: "https://flagcdn.com/32x24/lk.webp",
  },
  {
    code: "SD",
    dialCode: "+249",
    flag: "SD",
    name: "Sudan",
    flagSvg: "https://flagcdn.com/32x24/sd.webp",
  },
  {
    code: "SR",
    dialCode: "+597",
    flag: "SR",
    name: "Suriname",
    flagSvg: "https://flagcdn.com/32x24/sr.webp",
  },
  {
    code: "SJ",
    dialCode: "+47",
    flag: "SJ",
    name: "Svalbard and Jan Mayen",
    flagSvg: "https://flagcdn.com/32x24/sj.webp",
  },
  {
    code: "SE",
    dialCode: "+46",
    flag: "SE",
    name: "Sweden",
    flagSvg: "https://flagcdn.com/32x24/se.webp",
  },
  {
    code: "CH",
    dialCode: "+41",
    flag: "CH",
    name: "Switzerland",
    flagSvg: "https://flagcdn.com/32x24/ch.webp",
  },
  {
    code: "SY",
    dialCode: "+963",
    flag: "SY",
    name: "Syria",
    flagSvg: "https://flagcdn.com/32x24/sy.webp",
  },
  {
    code: "TW",
    dialCode: "+886",
    flag: "TW",
    name: "Taiwan",
    flagSvg: "https://flagcdn.com/32x24/tw.webp",
  },
  {
    code: "TJ",
    dialCode: "+992",
    flag: "TJ",
    name: "Tajikistan",
    flagSvg: "https://flagcdn.com/32x24/tj.webp",
  },
  {
    code: "TZ",
    dialCode: "+255",
    flag: "TZ",
    name: "Tanzania",
    flagSvg: "https://flagcdn.com/32x24/tz.webp",
  },
  {
    code: "TH",
    dialCode: "+66",
    flag: "TH",
    name: "Thailand",
    flagSvg: "https://flagcdn.com/32x24/th.webp",
  },
  {
    code: "TL",
    dialCode: "+670",
    flag: "TL",
    name: "Timor-Leste",
    flagSvg: "https://flagcdn.com/32x24/tl.webp",
  },
  {
    code: "TG",
    dialCode: "+228",
    flag: "TG",
    name: "Togo",
    flagSvg: "https://flagcdn.com/32x24/tg.webp",
  },
  {
    code: "TK",
    dialCode: "+690",
    flag: "TK",
    name: "Tokelau",
    flagSvg: "https://flagcdn.com/32x24/tk.webp",
  },
  {
    code: "TO",
    dialCode: "+676",
    flag: "TO",
    name: "Tonga",
    flagSvg: "https://flagcdn.com/32x24/to.webp",
  },
  {
    code: "TT",
    dialCode: "+1868",
    flag: "TT",
    name: "Trinidad and Tobago",
    flagSvg: "https://flagcdn.com/32x24/tt.webp",
  },
  {
    code: "TN",
    dialCode: "+216",
    flag: "TN",
    name: "Tunisia",
    flagSvg: "https://flagcdn.com/32x24/tn.webp",
  },
  {
    code: "TR",
    dialCode: "+90",
    flag: "TR",
    name: "Turkey",
    flagSvg: "https://flagcdn.com/32x24/tr.webp",
  },
  {
    code: "TM",
    dialCode: "+993",
    flag: "TM",
    name: "Turkmenistan",
    flagSvg: "https://flagcdn.com/32x24/tm.webp",
  },
  {
    code: "TC",
    dialCode: "+1649",
    flag: "TC",
    name: "Turks and Caicos Islands",
    flagSvg: "https://flagcdn.com/32x24/tc.webp",
  },
  {
    code: "TV",
    dialCode: "+688",
    flag: "TV",
    name: "Tuvalu",
    flagSvg: "https://flagcdn.com/32x24/tv.webp",
  },
  {
    code: "UG",
    dialCode: "+256",
    flag: "UG",
    name: "Uganda",
    flagSvg: "https://flagcdn.com/32x24/ug.webp",
  },
  {
    code: "UA",
    dialCode: "+380",
    flag: "UA",
    name: "Ukraine",
    flagSvg: "https://flagcdn.com/32x24/ua.webp",
  },
  {
    code: "AE",
    dialCode: "+971",
    flag: "AE",
    name: "United Arab Emirates",
    flagSvg: "https://flagcdn.com/32x24/ae.webp",
  },
  {
    code: "GB",
    dialCode: "+44",
    flag: "GB",
    name: "United Kingdom",
    flagSvg: "https://flagcdn.com/32x24/gb.webp",
  },
  {
    code: "US",
    dialCode: "+1",
    flag: "US",
    name: "United States",
    flagSvg: "https://flagcdn.com/32x24/us.webp",
  },
  {
    code: "UY",
    dialCode: "+598",
    flag: "UY",
    name: "Uruguay",
    flagSvg: "https://flagcdn.com/32x24/uy.webp",
  },
  {
    code: "UZ",
    dialCode: "+998",
    flag: "UZ",
    name: "Uzbekistan",
    flagSvg: "https://flagcdn.com/32x24/uz.webp",
  },
  {
    code: "VU",
    dialCode: "+678",
    flag: "VU",
    name: "Vanuatu",
    flagSvg: "https://flagcdn.com/32x24/vu.webp",
  },
  {
    code: "VE",
    dialCode: "+58",
    flag: "VE",
    name: "Venezuela",
    flagSvg: "https://flagcdn.com/32x24/ve.webp",
  },
  {
    code: "VN",
    dialCode: "+84",
    flag: "VN",
    name: "Vietnam",
    flagSvg: "https://flagcdn.com/32x24/vn.webp",
  },
  {
    code: "WF",
    dialCode: "+681",
    flag: "WF",
    name: "Wallis and Futuna",
    flagSvg: "https://flagcdn.com/32x24/wf.webp",
  },
  {
    code: "YE",
    dialCode: "+967",
    flag: "YE",
    name: "Yemen",
    flagSvg: "https://flagcdn.com/32x24/ye.webp",
  },
  {
    code: "ZM",
    dialCode: "+260",
    flag: "ZM",
    name: "Zambia",
    flagSvg: "https://flagcdn.com/32x24/zm.webp",
  },
  {
    code: "ZW",
    dialCode: "+263",
    flag: "ZW",
    name: "Zimbabwe",
    flagSvg: "https://flagcdn.com/32x24/zw.webp",
  },
];

export default countryCodesData;
